insert into authors (id, author) values (101, 'Drucie Goodbourn');
insert into authors (id, author) values (102, 'Marcia Aggiss');
insert into authors (id, author) values (103, 'Giovanni Bigg');
insert into authors (id, author) values (104, 'Duffie Eynon');
insert into authors (id, author) values (105, 'Anselma McKennan');
insert into authors (id, author) values (106, 'Gert Kira');
insert into authors (id, author) values (107, 'Clerc Djakovic');
insert into authors (id, author) values (108, 'Stacee Elsy');
insert into authors (id, author) values (109, 'Dorotea Bonhill');
insert into authors (id, author) values (110, 'Minni Bunney');
insert into authors (id, author) values (111, 'Berty Gandley');
insert into authors (id, author) values (112, 'Raynard Tesdale');
insert into authors (id, author) values (113, 'Joanna Hutfield');
insert into authors (id, author) values (114, 'Dannie Glidder');
insert into authors (id, author) values (115, 'Timmie Adshede');
insert into authors (id, author) values (116, 'Fernando Neads');
insert into authors (id, author) values (117, 'Teddy Guilliland');
insert into authors (id, author) values (118, 'Paloma Grebert');
insert into authors (id, author) values (119, 'Kristos Usher');
insert into authors (id, author) values (120, 'Darcey Rohmer');
insert into authors (id, author) values (121, 'Cristie Isacsson');
insert into authors (id, author) values (122, 'Lindsay Coutthart');
insert into authors (id, author) values (123, 'Helyn Schneidar');
insert into authors (id, author) values (124, 'Bette-ann');
insert into authors (id, author) values (125, 'Dom Robuchon');
insert into books (author, authorId, title, priceOld, price) values ('Drucie Goodbourn',  101, 'exploit real-time e-commerce', '$203.23', '$43.37');
insert into books (author, authorId, title, priceOld, price) values ('Marcia Aggiss',  102, 'utilize real-time interfaces', '$260.31', '$35.96');
insert into books (author, authorId, title, priceOld, price) values ('Giovanni Bigg',  103, 'extend strategic e-services', '$272.00', '$151.04');
insert into books (author, authorId, title, priceOld, price) values ('Duffie Eynon',  104, 'iterate integrated solutions', '$271.58', '$141.40');
insert into books (author, authorId, title, priceOld, price) values ('Anselma McKennan',  105, 'cultivate magnetic e-commerce', '$278.43', '$54.44');
insert into books (author, authorId, title, priceOld, price) values ('Gert Kira',  106, 'architect vertical ROI', '$282.54', '$102.61');
insert into books (author, authorId, title, priceOld, price) values ('Clerc Djakovic',  107, 'disintermediate extensible architectures', '$295.38', '$181.27');
insert into books (author, authorId, title, priceOld, price) values ('Stacee Elsy',  108, 'extend leading-edge methodologies', '$283.08', '$97.96');
insert into books (author, authorId, title, priceOld, price) values ('Dorotea Bonhill',  109, 'integrate one-to-one systems', '$258.51', '$52.25');
insert into books (author, authorId, title, priceOld, price) values ('Minni Bunney',  110, 'revolutionize 24/7 infrastructures', '$260.79', '$33.69');
insert into books (author, authorId, title, priceOld, price) values ('Berty Gandley',  111, 'enhance innovative e-services', '$256.54', '$160.98');
insert into books (author, authorId, title, priceOld, price) values ('Raynard Tesdale',  112, 'maximize 24/365 e-tailers', '$262.07', '$34.06');
insert into books (author, authorId, title, priceOld, price) values ('Joanna Hutfield',  113, 'scale integrated architectures', '$257.66', '$32.97');
insert into books (author, authorId, title, priceOld, price) values ('Dannie Glidder',  114, 'e-enable frictionless web services', '$288.19', '$90.52');
insert into books (author, authorId, title, priceOld, price) values ('Timmie Adshede',  115, 'strategize B2B channels', '$232.27', '$44.83');
insert into books (author, authorId, title, priceOld, price) values ('Fernando Neads',  116, 'syndicate compelling deliverables', '$287.45', '$101.89');
insert into books (author, authorId, title, priceOld, price) values ('Teddy Guilliland',  117, 'utilize bleeding-edge users', '$281.37', '$146.21');
insert into books (author, authorId, title, priceOld, price) values ('Paloma Grebert',  118, 'cultivate 24/365 networks', '$270.99', '$184.76');
insert into books (author, authorId, title, priceOld, price) values ('Kristos Usher',  119, 'embrace plug-and-play platforms', '$278.36', '$77.71');
insert into books (author, authorId, title, priceOld, price) values ('Darcey Rohmer',  120, 'target innovative paradigms', '$298.94', '$130.01');
insert into books (author, authorId, title, priceOld, price) values ('Cristie Isacsson',  121, 'generate open-source e-business', '$276.57', '$113.25');
insert into books (author, authorId, title, priceOld, price) values ('Lindsay Coutthart',  122, 'implement user-centric e-markets', '$254.70', '$115.31');
insert into books (author, authorId, title, priceOld, price) values ('Helyn Schneidar',  123, 'utilize magnetic supply-chains', '$279.70', '$77.86');
insert into books (author, authorId, title, priceOld, price) values ('Bette-ann Askem', 124, 'e-enable dot-com supply-chains', '$297.83', '$110.15');
insert into books (author, authorId, title, priceOld, price) values ('Dom Robuchon',  125, 'facilitate efficient eyeballs', '$232.30', '$131.48');
